// NAIVE IMPLEMENTATION OF A PET PROFILE
let buttons = {
    name: "Buttons",
    type : "miniature horse",
    age: 10,
    greeting: "sniff sniff",
    walk: "clip clop, clip clop",
}
// WHY IS THE ABOVE NOT IDEAL?

// OBJECT-ORIENTED IMPLEMENTATION OF A ANIMAL CLASS
class Animal {

    //ADD METHODS TO ANIMAL CLASS

    // ADD MULTIPLE METHODS TO OUR CLASS AND PASS THEM ARGUEMENTS

    // CREATE PROPERTIES ON OUR CLASSES INSIDE THE CONSTRUCTOR

    // CUSTOMIZE EACH INSTANCE (PROPERTIES AND METHODS) OF OUR CLASS

    // ADD DEFAULT VALUES TO OUR INSTANCES (IN CONSTRUCTOR)

    // MODIFY OUR METHOODS SO THAT OUR OBJECTS CAN INTERACT WITH OTHER OBJECTS

}
//WHY IS THIS BETTER?

// CONSOLE.LOG NEW INSTANCES OF OUR CLASS

// INVOKE INSTANCE METHODS ON OUR NEW INSTANCES OF THE ANIMAL CLASS

// INITIALIZE NEW INSTANCES OF OUR NOW CUSTOMIZABLE CLASS PASSING IT PARAMETERS



